name: Python application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 .
    - name: Test with pytest
      run: |
        pipenv run pytest pyprojat --cov=pyprojat
    - name: Posting Coverage
      env:
        CODECOV_TOKEN: "8a995a80-d3a6-41d4-b011-817d80c9868b"
      run: |
        pipenv run codecov