name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    - name: Instalar dependências
      run: |
        pip install -q -r requirements-dev.txt codecov
    - name: Rodar flake8
      uses: py-actions/flake8@v1
      with:
        checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
    - name: Test with pytest
      run: pytest libpythonpro_valmeida90 --cov=libpythonpro_valmeida90

    - name: Relátorio Covarege
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
      run: |
        codecov
      env:
        CODECOV_TOKEN=: '8a995a80-d3a6-41d4-b011-817d80c9868b'



